return {
  { 'nvim-mini/mini.notify',
		version = false,
		opts = {},
	},
  { 'nvim-mini/mini.surround',
		version = false,
		opts = {},
	},
  { 'nvim-mini/mini.pairs',
		version = false,
		opts = {},
	},
  { 'nvim-mini/mini.move',
		version = false,
		opts = {},
	},
  { 'nvim-mini/mini.indentscope',
		version = false,
		opts = {},
	},
}
